### ISSUE TITLE
 Rails 7.1: mock_model is not always === the class it mocks

### ISSUE THREAD

**Issue by bquorning** [rspec/rspec-activemodel-mocks#60]
#54 reported, and #55 fixed an issue where Rails 7.1 has removed the `ActiveRecord::Base#===` method. We found that the issue is only fixed in _some_ cases, but not all. Specifically, when you have multiple mock_model’s in the same spec file, `#===` only gets implemented on the first instance.

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "rspec-activemodel-mocks"
  gem "rspec"
  gem "sqlite3"
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define { create_table(:posts) }

Post = Class.new(ActiveRecord::Base)

require "rspec/autorun"

RSpec.describe "#===" do
  before do
    @foo = mock_model(Post)
    @bar = mock_model(Post)
    @baz = mock_model(Post)
  end

  it "works for the first mock_model" do
    expect(Post === @foo).to be(true)
  end

  it "works for the second mock_model" do
    expect(Post === @bar).to be(true)
  end

  it "works for the third mock_model" do
    expect(Post === @baz).to be(true)
  end
end
```

The output from running this file is

```
Failures:

  1) #=== works for the second mock_model
     Failure/Error: expect(Post === @bar).to be(true)
     
       expected true
            got false
     # repro.rb:35:in `block (2 levels) in <main>'

  2) #=== works for the third mock_model
     Failure/Error: expect(Post === @baz).to be(true)
     
       expected true
            got false
     # repro.rb:39:in `block (2 levels) in <main>'

Finished in 0.0144 seconds (files took 0.22345 seconds to load)
3 examples, 2 failures

Failed examples:

rspec repro.rb:34 # #=== works for the second mock_model
rspec repro.rb:38 # #=== works for the third mock_model
```

**Comment by JonRowe** [comment]
If you'd like to tackle this please do so and I'd be happy to review, but I don't have enough free time right now to look into it myself (and I don't really use this library).
